services:
  postgres:
    image: 'postgres:latest'
    environment:
        POSTGRES_DB: tb_links
        POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
        POSTGRES_USER: ${USERNAME_POSTGRES}
    ports:
      - '5432:5432'